config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }
  root 'tests#index'

  get 'all_badges', to: 'user_badges#all_badges'

  resources :feedbacks, only: %i[new create]
  resources :user_badges, only: %i[index]

  resources :tests, only: :index do
    member do
      post :start
    end
  end
  #GET user_passed_test/10/result
  resources :user_passed_tests, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true do
        resources :answers, shallow: true, except: :index
      end
    end
  end

  namespace :admin do
    resources :badges
    resources :gists, shallow: true
  end
end

app/models/admin.rb
class Admin < User
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validate :validate_count_answers, on: :create

  scope :correct, -> { where(correct: true) }

  private

  def validate_count_answers
    errors.add(:answers_limit, "Maximum 4 answers") if question.answers.count >= 4
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  enum rule: { category_complete: 1, level_complete: 2, first_try: 3 }
  has_many :user_badges
  has_many :users, through: :user_badges
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tests, dependent: :destroy
  validates :title, presence: true
  default_scope { order(title: :asc) }
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :user

  validates :title, :body, presence: true
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists
  validates :body, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :category
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'
  has_many :questions, dependent: :destroy
  has_many :user_passed_tests, dependent: :nullify
  has_many :users, through: :user_passed_tests

  validates :title, presence: true,
                    uniqueness: { scope: :level }
  validates :level, numericality: { only_integer: true, greater_than: 0 }

  scope :easy, -> { where(level: 0..1) }
  scope :normal, -> { where(level: 2..4) }
  scope :hard, -> { where(level: 5..Float::INFINITY) }
  scope :by_category, ->(title){ joins(:category).where(categories: { title: title }) }

  def self.by_category(title)
    by_category(title).order(title: :desc).pluck(:title)
  end

  def timer?
    timer.positive?
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable,
         :confirmable

  has_many :user_passed_tests
  has_many :tests, through: :user_passed_tests
  has_many :author_tests, class_name: "Test"
  has_many :gists
  has_many :feedbacks
  has_many :user_badges
  has_many :badges, through: :user_badges

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 80 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true

  def test_passage(level)
    tests.where(level: level)
  end

  def user_passed_test(test)
    user_passed_tests.order(id: :desc).find_by(test_id: test.id)
  end

  def admin?
    self.is_a?(Admin)
  end
 end

app/models/user_badge.rb
class UserBadge < ApplicationRecord
  belongs_to :user
  belongs_to :badge
end

app/models/user_passed_test.rb
class UserPassedTest < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_first_question, on: :create

  scope :by_level, ->(level) { joins(:test).where(tests: { level: level }) }
  scope :by_category, ->(category) { joins(:test).where(tests: { category: category }) }

  DONE_PERCENT = 85

  def completed?
    current_question.nil?
  end

  def accept!(answer_ids)
    if correct_answer?(answer_ids)
      self.correct_questions += 1
    end

    self.current_question = next_question
    save!
  end

  def result
    100 * self.correct_questions / test.questions.count
  end

  def success?
    result >= DONE_PERCENT
  end

  def current_question_number
    test.questions.count - test.questions.order(:id).where('id > ?', current_question.id).count
  end

  def done?
    completed? && success?
  end

  def time_left
    (active_time - Time.current).to_i
  end

  def time_over?
    Time.current > active_time
  end

  def active_time
    created_at + test.timer.seconds
  end

  private

  def before_validation_set_first_question
    if test.present?
      self.current_question = test.questions.first
    else
      self.current_question = next_question
    end
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question.id).first
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_test, only: %i[start]

  def index
    @tests = Test.all
  end

  def start
    if @test.questions.present?
      current_user.tests.push(@test)
      redirect_to current_user.user_passed_test(@test)
    else
      redirect_to root_path, alert: "Sorry, but this test has no questions!"
    end
  end

  private

  def find_test
    @test = Test.find(params[:id])
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  ALERT_TYPE = {
    notice: 'alert-info',
    success: 'alert-success',
    error: 'alert-danger',
    alert: 'alert-warning'
  }

  def current_year
    Date.current.year
  end

  def github_url(author, repo)
    content_tag(:a, 'project', href: "https://github.com/#{author}/#{repo}", target: '_blank')
  end

  def alert_style(type)
    ALERT_TYPE.fetch(type.to_sym, 'alert-info')
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    if question.persisted?
      "Edit #{question.test.title} question"
    else
      "Create #{question.test.title} question"
    end
  end

end

app/helpers/tests_helper.rb
module TestsHelper

  def questions_count(test)
    test.questions.count
  end

end

app/helpers/user_badges_helper.rb
module UserBadgesHelper
end

app/views/admin/_admin_header.html.erb
<header class='navbar'>
  <div class='container'>
    <%= link_to "TestGuru Admin Panel", root_path, id: :logo %>
    <nav>
      <ul class='nav'>
        <% if user_signed_in? %>
          <p class="nav user">
            <%= t('.welcome', name: current_user.first_name) %> |
            <%= link_to t('.logout'), destroy_user_session_path, method: :delete %> |
            <%= link_to 'Gists', admin_gists_path %> |
            <%= link_to 'Badges', admin_badges_path %>
          </p>
        <% else %>
          <li><%= link_to t('navbar.join_to_guru'), new_user_registration_path %></li>
          <li><%= link_to t('navbar.login'), new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_errors.html.erb
<% if resource.present? && resource.errors.present? %>
  <%= content_tag :div, class: 'resource-errors', data: { resource_id: resource.id } do %>
      <h2><%= t('.header', count: resource.errors.count) %>:</h2>

      <ul>
          <% resource.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
      </ul>
  <% end %>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |key, message| %>
  <%= content_tag :div, message, class: "alert #{alert_style(key)}" %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav class="navbar navbar-default navbar-custom">
    <div class="container">
      <small>
        The training <%= github_url('alexrails', 'testguru') %> by <a href="https://thinknetica.com/" target="_blank">Thinknetica</a>
        courses. Author <a href="https://github.com/alexrails" target="_blank">Alex Korzun</a>
        This application allows you to create, manage and run tests. Designed as part of Thinknetica courses.
        <p><%= current_year %></p>
      </small>
    </div>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class='navbar'>
  <div class='container'>
    <%= link_to "TestGuru", root_path, id: :logo %>
    <nav>
      <ul class='nav'>
        <% if user_signed_in? %>
          <li>
            <% if current_user.admin? %>
              <%= link_to t('.admin_panel'), admin_tests_path %> |
              <%= link_to 'Gists', admin_gists_path %> |
            <% end %>
            <%= t('.welcome', name: current_user.first_name) %> |
            <%= link_to t('.logout'), destroy_user_session_path, method: :delete %> |
            <%= link_to t('navbar.feedback'), new_feedback_path %> |
            <%= link_to 'My badges', user_badges_path %> |
            <%= link_to 'All badges', all_badges_path %>
          </li>
        <% else %>
          <li><%= link_to t('navbar.join_to_guru'), new_user_registration_path %></li>
          <li><%= link_to t('navbar.login'), new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin Panel | Testguru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'admin/admin_header' %>
    <div class="container">
    <%= render 'layouts/flash' %>
    <%= yield %>
  </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Testguru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <div class="container">
      <%= render 'layouts/flash' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>