config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }
  root 'tests#index'

  get 'all_badges', to: 'user_badges#all_badges'

  resources :feedbacks, only: %i[new create]
  resources :user_badges, only: %i[index]

  resources :tests, only: :index do
    member do
      post :start
    end
  end
  #GET user_passed_test/10/result
  resources :user_passed_tests, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member
      resources :questions, shallow: true do
        resources :answers, shallow: true, except: :index
      end
    end
  end

  namespace :admin do
    resources :badges
    resources :gists, shallow: true
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists
  validates :body, presence: true
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::BaseController

  before_action :find_test, only: %i[index new create]
  before_action :find_question, only: %i[show update edit destroy]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_question_not_found

  def index
  end

  def show
  end

  def new
    @question = @test.questions.new
  end

  def edit
  end

  def create
    @question = @test.questions.new(question_params)
    if @question.save
      redirect_to admin_question_path(@question)
    else
      render :new
    end
  end

  def update
    if @question.update(question_params)
      redirect_to admin_question_path(@question)
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to admin_test_path(@question.test_id)
  end

  def find_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:body)
  end

  def find_test
    @test = Test.find(params[:test_id])
  end

  def rescue_question_not_found
    render plain: "Question not found!"
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    if question.persisted?
      "Edit #{question.test.title} question"
    else
      "Create #{question.test.title} question"
    end
  end

end

app/views/admin/questions/_errors.html.erb
  <% if @question.errors.present? %>
    <div>
      <h2>Errors detected:</h2>
      <h2><%= pluralize(@question.errors.count, 'error') %> detected:</h2>

      <ul>
          <% @question.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
      </ul>
    </div>
  <% end %>

app/views/admin/questions/_form.html.erb
<h3><%= question_header(@question) %></h3>

<%= form_with model: [:admin, @test, @question], local: true do |f| %>

  <%= render 'errors' %>
  <div class="form-group">
    <p>
      <%= f.label "Question's body" %>
      <%= f.text_field :body, id: 'question[body]', class: 'form-control' %>
    </p>

    <p><%= f.submit class: 'btn btn-light' %></p>
  </div>
<% end %>

app/views/admin/questions/edit.html.erb
<%= render 'form' %>

app/views/admin/questions/index.html.erb
<h1>Listening questions</h1>

<table>
  <thead>
    <tr>
      <th>Test_id</th>
      <th>Question</th>
    </tr>
  </thead>

  <% @test.questions.each do |question| %>
    <tr>
      <td><%= question.test_id %></td>
      <td><%= question.body %></td>
      <td><%= link_to 'Delete question', admin_question_path(question),
        method: :delete,
        data: { confirm: "You sure?"  } %></td>
    </tr>
  <% end %>
  </table>

app/views/admin/questions/new.html.erb
<%= render 'form' %>
<p>
  <%= link_to 'Back', admin_test_path(@question.test) %>
</p>

app/views/admin/questions/show.html.erb
<h3>Question #<%= @question.id%></h3>
<b><%= @question.body %></b>
<hr class="my-4">
<b>Answers</b>
<p><%= link_to 'New answers', new_admin_question_answer_path(@question), class: 'btn btn-light' %></p>
<ol class="list-group list-group-flush">
  <%= render @question.answers %>
</ol>

<p><%= link_to 'Edit', edit_admin_question_path(@question), class: 'btn btn-secondary' %>
   <%= link_to 'Back', admin_test_path(@question.test), class: 'btn btn-secondary' %></p>